name: .NET Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release --no-restore

      - name: Run tests
        run: dotnet test --configuration Release --no-build --collect:"XPlat Code Coverage"

      - name: Publish test results
        uses: actions/upload-artifact@v2
        with:
          name: Test Results
          path: TestResults

      - name: Upload code coverage report
        uses: actions/upload-artifact@v2
        with:
          name: Code Coverage
          path: TestResults/$(Agent.OS)/$(Build.Repository.Name)/coverage.cobertura.xml
